spring:
  datasource:
    url: jdbc:mysql://localhost:3306/supplier_service
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      host: localhost
      port: 6379
mybatis:
  configuration:
    map-underscore-to-camel-case: true #开启大小写转换
